[package]
name = "verilog-format"
version = "0.1.0"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"

[dependencies]
nom = "5.0.1"
regex = "1"
clap = "2.32"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
